{% set version = "1.2.1" %}

package:
  name: ecsimplesnow
  version: {{ version }}

source:
  url: https://github.com/permamodel/Snow_BMI_Fortran/archive/v{{ version }}.tar.gz
  sha256: 9b7d3ac77de2d88d0e9017ec66e7d4fc9f46137c5570d5397d2512e4e62a9d77

build:
  number: 1
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('cxx') }}  # [win]
    - {{ stdlib("c") }}  # [win]
    - cmake
    - make  # [unix]
  host:
    - cmake
    - bmi-fortran

test:
  source_files:
    - data
  commands:
    - cp data/tair.csv data/test_tair.csv
    - cp data/prec.csv data/test_prec.csv
    - run_bmisnow_model data/snow_model_test.cfg

about:
  home: https://csdms.colorado.edu/wiki/Model:ECSimpleSnow
  license: Apache-2.0
  license_file: LICENSE
  summary: A simple snow model
  description: |
    ECSimpleSnow is a simple snow model cooperatively developed by
    Kang Wang (University of Colorado Boulder), Ross Brown
    (Environment Canada), and Bruce Brasnett (Canadian Meteorological
    Centre). It employs an empirical algorithm to melt or accumulate
    snow based on surface temperature and precipitation that has
    fallen since the previous analysis step.
  doc_url: https://csdms.colorado.edu/wiki/Model:ECSimpleSnow
  dev_url: https://github.com/permamodel/Snow_BMI_Fortran

extra:
  recipe-maintainers:
    - mdpiper
