travis:
  secure:
    BINSTAR_TOKEN: jt1GwunZtizhokRrhqROJ+psIicYcqfoOlbb52DTEP1cNDECALwQIv2phdeZHtIx13AYwvDz+FolYE8Mg5ZAQrPpB8bwn45+ugsXAOwvnz0Zi2bieqTrpl/yxedRbp1Z6u/1wVN45ccaeeKQNA5zfuu7RHgbUdxlAFDdnylWQKa0vBIbbvkG4g7cTX6Yxh0qn725ICPbsdd2BhCM4C1zr3oG/79Ed8+86KsL8M+OJgu2XYOc59hTVTzgiG+fGtbHkUqwfQMMkpvMEdxSS1J+uin6fIno9YjRnbr/LCHK2/lt/gU9VGKhjA0buYTHHk/oZuKRcdogZUlsMBJKri3NZDNlSnf3slcsQ2jDKi0zGUqJAs0w7ONOyRS8SFbKxIG3DYBHqAVTceBTuBP8q2D2NmPyeZdIs25iD8w1yohEgMKwmEfWOXKvzg1XXsxOmoOjw/Y0vnjQ6QWGqQkY9D10zm/+36y+gYvJjajkPSVdF+0ijcsDB1qP9vLWVTc+41SzQr6VKqnnvIiGHTPmziQKgww6oNf0TxOliqVp6fwxpD+UVhxlqSs2mVkq3dM/FBxFfcDT1Cp4ap9vlWcjixaF5J5PnqiBmHh5FlD1E+o9KAtYNHK955UkAMbZzS0fYDpyrj/HM0EtptN2j1vFvVSxF99RSpL8NffKHEXOFch6grs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
